default: &default 
  adapter: postgresql 
  encoding: unicode 
  pool: 5
  username: kogo
  password:

development:
  <<: *default
  database: propeller_db

test:
  <<: *default 
  database: propeller_test
